import { Inter } from "next/font/google";
import "./globals.css";
import NavBarLeft from "./components/NavBarLeft";
import NavBarTop from "./components/NavBarTop";
import DuaCategories from "./components/DuaCategories";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-slate-200">
      <body className={inter.className}>
        <div>
          <div className="customContainer ">
            <div className="col-span-1 row-span-2 lg:ml-4">
              {/* <p>navBarLeft</p> */}
              <NavBarLeft />
            </div>

            <div className="navBarTop">
              {/* <p>navBarTop</p> */}
              <NavBarTop />
            </div>
            <div className="h-fit">
              {/* <p>Categories</p> */}
              <DuaCategories />
            </div>
            <div className="h-fit">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
