import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="customContainer">
            <div className="navBarLeft">
              <p>navBarLeft</p>
            </div>

            <div className="navBarTop">
              <p>navBarTop</p>
            </div>
            <div className="h-fit">
              <p>Categories</p>
            </div>
            <div className="h-fit">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
